apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  labels:
    name: connector
spec:
  replicas: {{ .Values.connector.replicas }}
  selector:
    matchLabels:
      name: connector
  template:
    metadata:
      labels:
        name: connector
    spec:
      initContainers:
        - name: wait-for-controller
          image: fmiguelez/alpine-curl-jq:latest
          env:
            - name: CONTROLLER_URL
              value: "http://{{ .Values.controller.host }}:{{ .Values.controller.port }}/api/v3"
          command: ['sh', '-c']
          args:
          - |
            until [[ "$(curl ${CONTROLLER_URL}/status 2>/dev/null | jq -r ".status")" == "online" ]]; do
              echo "Waiting for Controller at ${CONTROLLER_URL}..."
              sleep 2
            done
      containers:
      - name: connector
        image: {{ .Values.connector.image }}
        imagePullPolicy: {{ .Values.connector.imagePullPolicy }}
---
kind: Service
apiVersion: v1
metadata:
  name: connector
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  labels:
    name: connector
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.connector.port }}
      targetPort: {{ .Values.connector.port }}
      protocol: TCP
      name: connector
{{range $i, $e := untilStep 6000 6051 1}}
    - port: {{$e}}
      targetPort: {{$e}}
      protocol: TCP
      name: connector{{$i}}
{{end}}
  selector:
    name: connector
