apiVersion: iofog.org/v3
kind: ControlPlane
metadata:
  name: iofog
spec:
  user:
    name: {{ .Values.controlPlane.user.firstName }}
    surname: {{ .Values.controlPlane.user.surname }}
    email: {{ .Values.controlPlane.user.email }}
    password: {{ .Values.controlPlane.user.password | b64enc }}
  database:
    provider: {{ .Values.controlPlane.database.provider | quote }}
    host: {{ .Values.controlPlane.database.host | quote }}
    port: {{ .Values.controlPlane.database.port | default 0 }}
    user: {{ .Values.controlPlane.database.user | quote }}
    password: {{ .Values.controlPlane.database.password | quote }}
    databaseName: {{ .Values.controlPlane.database.dbName | quote }}
  replicas:
    controller: {{ .Values.controlPlane.controller.replicas }}
  images:
    controller: {{ .Values.controlPlane.controller.image }}
    proxy: {{ .Values.controlPlane.proxyImage }}
    router: {{ .Values.controlPlane.routerImage }}
    portManager: {{ .Values.controlPlane.portManagerImage }}
  services:
  {{- if eq .Values.controlPlane.ingressLoadBalancerIP "" }}
    controller:
      type: "LoadBalancer"
    router:
      type: "LoadBalancer"
    proxy:
      type: "LoadBalancer"
  {{ else }}
    controller:
      type: "ClusterIP"
    router:
      type: "ClusterIP"
    proxy:
      type: "ClusterIP"
  {{ end }}
      address: {{ .Values.controlPlane.ingressLoadBalancerIP | quote }}
  controller:
    pidBaseDir: {{ .Values.controlPlane.controller.pidBaseDir }}
    ecnViewerPort: {{ .Values.controlPlane.controller.ecnViewerPort }}
