{{ if .Values.createCustomResource }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iofogs.k8s.iofog.org
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: k8s.iofog.org
  names:
    kind: IOFog
    listKind: IOFogList
    plural: iofogs
    singular: iofog
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.k8s.iofog.org
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: k8s.iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
{{ end }}
