apiVersion: v1
kind: ServiceAccount
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: iofog-operator
  template:
    metadata:
      labels:
        name: iofog-operator
    spec:
      serviceAccountName: iofog-operator
      containers:
        - name: iofog-operator
          image: {{ .Values.operator.image }}
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - iofog-operator
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iofog-operator"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace | default .Values.defaultNamespace }}-iofog-operator
subjects:
  - kind: ServiceAccount
    name: iofog-operator
    namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io