---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iofog-operator
subjects:
- kind: ServiceAccount
  name: iofog-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - iofog.org
  resources:
  - applications
  - controlplanes
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - serviceaccounts
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - '*'
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: iofog-operator
  template:
    metadata:
      labels:
        name: iofog-operator
    spec:
      serviceAccountName: iofog-operator
      containers:
        - name: iofog-operator
          image: {{ .Values.operator.image }}
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - iofog-operator
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iofog-operator"
